/**
 * BetterAuth configuration — V2-001-T2 / T3 / T4
 *
 * Plugins wired here: emailAndPassword (built-in), genericOAuth, organization, apiKey.
 *
 * ── CLI vs runtime split (T3) ────────────────────────────────────────────────
 * BetterAuth CLI (`auth generate`) runs via `jiti` and executes this module at
 * schema-generation time, outside the Next.js runtime. The three-tier resolver
 * requires the database to be available (for provenance writes) and is only
 * fully initialised after instrumentation.ts has called configResolver.resolve().
 *
 * To avoid blocking the CLI on DB availability, this module uses a two-path
 * approach:
 *   - During `auth generate` (NEXT_RUNTIME is undefined): reads directly from
 *     process.env, exactly as BetterAuth expects for schema generation.
 *   - During Next.js application runtime: reads from the resolver singleton,
 *     which was populated by instrumentation.ts before any request handler runs.
 *
 * The resolver's values take precedence at runtime; the env-var fallback is
 * only ever used by the CLI and in early-boot scenarios before resolve() fires.
 *
 * TODOs for later tasks:
 *   - T5: Tune apiKey options (prefix, expiration, rate limits, scoped permissions for
 *         extension, Courier, and programmatic callers).
 *   - T6: Consume instance UUID generated by Instance Identity bootstrap here if needed.
 *
 * Database adapter note:
 *   The project supports both SQLite (default local dev) and Postgres (production /
 *   `DATABASE_URL=postgres://...`). The adapter provider is sniffed from DATABASE_URL
 *   at startup to match the Drizzle client dialect. For Postgres deployments the auth
 *   schema tables must be created via the same Drizzle migration pipeline.
 */

import { betterAuth } from 'better-auth';
import { drizzleAdapter } from 'better-auth/adapters/drizzle';
import { createAuthMiddleware } from 'better-auth/api';
import { genericOAuth } from 'better-auth/plugins/generic-oauth';
import { organization } from 'better-auth/plugins/organization';
import { apiKey } from '@better-auth/api-key';
import { eq } from 'drizzle-orm';
import { getDb } from '../db/client';
import * as authSchema from '../db/schema.auth';
import { hashPassword, verifyPassword } from './password';

/**
 * Resolves the BetterAuth config values including OIDC and password-login mode.
 *
 * At Next.js runtime, reads from the singleton ConfigResolver which was
 * populated in instrumentation.ts. Falls back to direct env-var reads so
 * that `auth generate` (CLI / jiti execution) continues to work without
 * a running database or a resolved config.
 */
function getAuthConfig(): {
  secret: string | undefined;
  baseURL: string;
  passwordLoginEnabled: boolean;
  oidcIssuerUrl: string | undefined;
  oidcClientId: string | undefined;
  oidcClientSecret: string | undefined;
  oidcAdminGroupClaim: string;
} {
  // Attempt resolver path first (application runtime).
  // We guard with a try/catch so the CLI does not crash if the resolver
  // has not been initialised (e.g. during `npx @better-auth/cli generate`).
  try {
    // Dynamic require-style import avoids jiti resolving the full module graph
    // at schema-generation time. At Next.js runtime this path always succeeds.
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const mod = require('../config/index') as typeof import('../config/index');
    const resolver = mod.configResolver;
    // resolver.getResolved() returns null if resolve() has not been called yet.
    const resolved = resolver.getResolved();
    if (resolved) {
      return {
        secret: resolved.BETTER_AUTH_SECRET,
        baseURL: resolved.BETTER_AUTH_URL,
        passwordLoginEnabled: resolved.PASSWORD_LOGIN_ENABLED,
        oidcIssuerUrl: resolved.OIDC_ISSUER_URL,
        oidcClientId: resolved.OIDC_CLIENT_ID,
        oidcClientSecret: resolved.OIDC_CLIENT_SECRET,
        oidcAdminGroupClaim: resolved.OIDC_ADMIN_GROUP_CLAIM,
      };
    }
  } catch {
    // CLI context — resolver module cannot be loaded or has not been initialised.
  }

  // Fallback: direct env-var reads (CLI / pre-resolve startup path).
  return {
    secret: process.env.BETTER_AUTH_SECRET,
    baseURL: process.env.BETTER_AUTH_URL ?? 'http://localhost:7393',
    // Default to enabled so CLI schema-gen and pre-boot paths are safe.
    passwordLoginEnabled: process.env.PASSWORD_LOGIN_ENABLED !== 'false',
    oidcIssuerUrl: process.env.OIDC_ISSUER_URL,
    oidcClientId: process.env.OIDC_CLIENT_ID,
    oidcClientSecret: process.env.OIDC_CLIENT_SECRET,
    oidcAdminGroupClaim: process.env.OIDC_ADMIN_GROUP_CLAIM ?? 'admin',
  };
}

const dbUrl = process.env.DATABASE_URL ?? 'file:./lootgoblin.db';
const dbProvider = dbUrl.startsWith('postgres') ? 'pg' : 'sqlite';

const {
  secret,
  baseURL,
  passwordLoginEnabled,
  oidcIssuerUrl,
  oidcClientId,
  oidcClientSecret,
  oidcAdminGroupClaim,
} = getAuthConfig();

// ── genericOAuth config ─────────────────────────────────────────────────────
// Populated when OIDC is configured; empty array = plugin active but no provider.
const oidcProviderConfig =
  oidcIssuerUrl && oidcClientId && oidcClientSecret
    ? [
        {
          providerId: 'oidc',
          clientId: oidcClientId,
          clientSecret: oidcClientSecret,
          discoveryUrl: `${oidcIssuerUrl}/.well-known/openid-configuration`,
          scopes: ['openid', 'email', 'profile', 'groups'],
          mapProfileToUser: async (profile: Record<string, unknown>) => ({
            email: profile.email as string,
            name:
              (profile.name as string | undefined) ??
              (profile.preferred_username as string | undefined) ??
              '',
            image: (profile.picture as string | undefined) ?? null,
          }),
        },
      ]
    : [];

// ── After-sign-in hook: OIDC group-to-role mapping ─────────────────────────
// On every OIDC login, re-evaluate the user's role from the `groups` claim so
// that adding/removing a user from the admin group in the IdP propagates on
// next login.  Non-OIDC sign-ins are ignored.
const afterSignInHook = createAuthMiddleware(async (ctx) => {
  // Only act on OAuth/OIDC sign-in callbacks.
  if (!ctx.path.startsWith('/sign-in/oauth2') && !ctx.path.startsWith('/callback/')) {
    return;
  }

  const newSession = ctx.context.newSession;
  if (!newSession) return;

  const userId = newSession.user.id;

  // Extract groups from the OAuth profile claim.
  // BetterAuth stores the raw token profile on ctx.body when going through
  // the OAuth callback flow; fall back to an empty array if absent.
  const rawGroups = (ctx.body as Record<string, unknown> | undefined)?.groups;
  const groups: string[] = Array.isArray(rawGroups)
    ? (rawGroups as unknown[]).map(String)
    : [];

  const desiredRole = groups.includes(oidcAdminGroupClaim) ? 'admin' : 'member';

  // Update the user's role in all organization memberships.
  // We use Drizzle directly here because auth.api.updateMemberRole requires a
  // session header — which we are in the process of creating.
  try {
    const db = getDb() as any;
    await db
      .update(authSchema.member)
      .set({ role: desiredRole })
      .where(eq(authSchema.member.userId, userId));
  } catch {
    // Non-fatal — group mapping best-effort; role will be corrected on next login.
  }
});

export const auth = betterAuth({
  baseURL,
  secret,

  database: drizzleAdapter(getDb(dbUrl), {
    provider: dbProvider,
    schema: authSchema,
    usePlural: false,
  }),

  emailAndPassword: {
    // Conditionally enabled: disabled in OIDC-only mode (PASSWORD_LOGIN_ENABLED=false).
    // During CLI schema-gen this defaults to true (env-fallback path).
    enabled: passwordLoginEnabled,
    password: {
      hash: hashPassword,
      verify: verifyPassword,
    },
  },

  hooks: {
    after: afterSignInHook,
  },

  plugins: [
    // Populated from ConfigResolver when OIDC is configured; no-op if empty.
    genericOAuth({ config: oidcProviderConfig }),

    // Household / instance multi-user shape per ADR-004 + ADR-007.
    // T4: tune allowUserToCreateOrganization, organizationLimit, membershipLimit.
    organization(),

    // Extension + Courier + programmatic pairing support per V2-001-T5.
    // T5: tune prefix, expiration defaults, rate limits, and per-scope permissions.
    apiKey(),
  ],
});

export type Auth = typeof auth;
