/**
 * BetterAuth configuration — V2-001-T2
 *
 * Plugins wired here: emailAndPassword (built-in), genericOAuth, organization, apiKey.
 *
 * TODOs for later tasks:
 *   - T3: Replace process.env reads with three-tier ConfigResolver (BETTER_AUTH_SECRET,
 *         BETTER_AUTH_URL) so they pick up file / env / DB overrides consistently.
 *   - T4: Wire argon2id custom hasher/verifier into emailAndPassword.password.*
 *         Currently uses BetterAuth's default scrypt hasher (safe but not argon2id).
 *   - T4: Populate genericOAuth.config[] with real provider entries from ConfigResolver
 *         (Authentik, Pocket-ID, Authelia, Keycloak). The empty array is a valid no-op.
 *   - T4: Add role-to-claim mapping and session enrichment after BetterAuth session hooks.
 *   - T5: Tune apiKey options (prefix, expiration, rate limits, scoped permissions for
 *         extension, Courier, and programmatic callers).
 *   - T6: Consume instance UUID generated by Instance Identity bootstrap here if needed.
 *
 * Database adapter note:
 *   The project supports both SQLite (default local dev) and Postgres (production /
 *   `DATABASE_URL=postgres://...`). The adapter provider is sniffed from DATABASE_URL
 *   at startup to match the Drizzle client dialect. For Postgres deployments the auth
 *   schema tables must be created via the same Drizzle migration pipeline.
 */

import { betterAuth } from 'better-auth';
import { drizzleAdapter } from 'better-auth/adapters/drizzle';
import { genericOAuth } from 'better-auth/plugins/generic-oauth';
import { organization } from 'better-auth/plugins/organization';
import { apiKey } from '@better-auth/api-key';
import { getDb } from '../db/client';
import * as authSchema from '../db/schema.auth';

const dbUrl = process.env.DATABASE_URL ?? 'file:./lootgoblin.db';
const dbProvider = dbUrl.startsWith('postgres') ? 'pg' : 'sqlite';

export const auth = betterAuth({
  // T3: Replace with ConfigResolver values once the three-tier resolver is in place.
  baseURL: process.env.BETTER_AUTH_URL ?? 'http://localhost:7393',
  secret: process.env.BETTER_AUTH_SECRET,

  database: drizzleAdapter(getDb(dbUrl), {
    provider: dbProvider,
    schema: authSchema,
    usePlural: false,
  }),

  emailAndPassword: {
    enabled: true,
    // T4: wire argon2id hasher/verifier here once T4 lands:
    //   password: { hash: argon2idHasher, verify: argon2idVerifier }
    // Using BetterAuth's default scrypt-based hasher for now (safe, not argon2id).
  },

  plugins: [
    // T4: populate config[] with real OIDC provider entries from ConfigResolver.
    // Empty array is valid — plugin registers the routes but no providers are active.
    genericOAuth({ config: [] }),

    // Household / instance multi-user shape per ADR-004 + ADR-007.
    // T4: tune allowUserToCreateOrganization, organizationLimit, membershipLimit.
    organization(),

    // Extension + Courier + programmatic pairing support per V2-001-T5.
    // T5: tune prefix, expiration defaults, rate limits, and per-scope permissions.
    apiKey(),
  ],
});

export type Auth = typeof auth;
