/**
 * V2-005e-T_e3: Sidecar-parser unit tests.
 *
 * Covers BOTH parse paths:
 *   - .gcode.3mf  → JSZip + fast-xml-parser (Bambu/Orca shape +
 *                   bare-attribute shape).
 *   - .gcode      → header-comment regex (first 8 KiB).
 *
 * NEVER throws: malformed inputs (non-zip / malformed XML / missing
 * source ref) all return null.
 */

import * as fsp from 'node:fs/promises';
import * as path from 'node:path';
import * as os from 'node:os';
import { describe, it, expect, beforeAll } from 'vitest';
import JSZip from 'jszip';

import { parseSidecar } from '../../src/forge/slice-pairings/sidecar-parser';

let scratch: string;

beforeAll(async () => {
  scratch = await fsp.mkdtemp(path.join(os.tmpdir(), 'lootgoblin-sidecar-'));
});

async function writeThreemfWithModelSettings(
  filename: string,
  xml: string,
): Promise<string> {
  const filePath = path.join(scratch, filename);
  const zip = new JSZip();
  zip.file('Metadata/model_settings.config', xml);
  const buf = await zip.generateAsync({ type: 'nodebuffer' });
  await fsp.writeFile(filePath, buf);
  return filePath;
}

describe('parseSidecar — .gcode.3mf', () => {
  it('extracts source_file from Bambu/Orca {key,value} attribute shape', async () => {
    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<config>
  <object id="1">
    <metadata key="source_file" value="cube.stl"/>
    <metadata key="extruder" value="0"/>
  </object>
</config>`;
    const filePath = await writeThreemfWithModelSettings('plate_1.gcode.3mf', xml);
    const hint = await parseSidecar(filePath);
    expect(hint).not.toBeNull();
    expect(hint!.sourceBasename).toBe('cube.stl');
  });

  it('extracts threeMfUuid when an object_id metadata is present', async () => {
    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<config>
  <object id="42">
    <metadata key="source_file" value="part.stl"/>
    <metadata key="object_id" value="abc-123"/>
  </object>
</config>`;
    const filePath = await writeThreemfWithModelSettings('part.gcode.3mf', xml);
    const hint = await parseSidecar(filePath);
    expect(hint?.threeMfUuid).toBe('abc-123');
  });

  it('returns null when model_settings.config is absent', async () => {
    const filePath = path.join(scratch, 'empty.gcode.3mf');
    const zip = new JSZip();
    zip.file('OtherFile.txt', 'irrelevant');
    await fsp.writeFile(filePath, await zip.generateAsync({ type: 'nodebuffer' }));
    expect(await parseSidecar(filePath)).toBeNull();
  });

  it('returns null for non-zip bytes', async () => {
    const filePath = path.join(scratch, 'not-a-zip.gcode.3mf');
    await fsp.writeFile(filePath, 'not-a-zip-just-text');
    expect(await parseSidecar(filePath)).toBeNull();
  });

  it('returns null when XML has no source_file/name reference', async () => {
    const xml = `<?xml version="1.0"?><config><object/></config>`;
    const filePath = await writeThreemfWithModelSettings('blank.gcode.3mf', xml);
    expect(await parseSidecar(filePath)).toBeNull();
  });
});

describe('parseSidecar — plain .gcode', () => {
  it('extracts source from header comment "; source = X"', async () => {
    const filePath = path.join(scratch, 'plain.gcode');
    await fsp.writeFile(
      filePath,
      [
        '; generated by Slicer 1.0',
        '; source = my_model.stl',
        'G28',
        'G1 X10 Y10',
      ].join('\n'),
    );
    const hint = await parseSidecar(filePath);
    expect(hint?.sourceBasename).toBe('my_model.stl');
  });

  it('extracts source from "; original_filename = X"', async () => {
    const filePath = path.join(scratch, 'orig.gcode');
    await fsp.writeFile(
      filePath,
      '; original_filename = thing.stl\nG28\n',
    );
    const hint = await parseSidecar(filePath);
    expect(hint?.sourceBasename).toBe('thing.stl');
  });

  it('returns null when no header comment carries the source', async () => {
    const filePath = path.join(scratch, 'no-source.gcode');
    await fsp.writeFile(filePath, '; just gcode\nG28\nG1 X1\n');
    expect(await parseSidecar(filePath)).toBeNull();
  });
});

describe('parseSidecar — extension dispatch', () => {
  it('returns null for unknown extensions', async () => {
    const filePath = path.join(scratch, 'note.txt');
    await fsp.writeFile(filePath, 'hello');
    expect(await parseSidecar(filePath)).toBeNull();
  });
});
