package sdcp

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net"
	"time"

	"github.com/gorilla/websocket"
)

// ---------------------------------------------------------------------------
// wsConn — thin interface over gorilla websocket.Conn for test injection.
// Mirrors the moonraker pattern.
// ---------------------------------------------------------------------------

// wsConn abstracts a WebSocket connection so tests can inject a fake.
type wsConn interface {
	ReadMessage() ([]byte, error)
	WriteMessage([]byte) error
	Close() error
}

// gorillaConn wraps *websocket.Conn to satisfy wsConn.
type gorillaConn struct {
	conn *websocket.Conn
}

func (g *gorillaConn) ReadMessage() ([]byte, error) {
	_, msg, err := g.conn.ReadMessage()
	return msg, err
}

func (g *gorillaConn) WriteMessage(msg []byte) error {
	return g.conn.WriteMessage(websocket.TextMessage, msg)
}

func (g *gorillaConn) Close() error {
	return g.conn.Close()
}

// ---------------------------------------------------------------------------
// Cmd 128 payload — pure message build
// ---------------------------------------------------------------------------

// startPrintPayload is the JSON shape of the SDCP Cmd 128 (start-print) message.
// Matches the shape in commander.ts exactly.
type startPrintPayload struct {
	ID    string              `json:"Id"`
	Data  startPrintDataOuter `json:"Data"`
	Topic string              `json:"Topic"`
}

type startPrintDataOuter struct {
	Cmd         int                `json:"Cmd"`
	Data        startPrintDataInner `json:"Data"`
	RequestID   string             `json:"RequestID"`
	MainboardID string             `json:"MainboardID"`
	TimeStamp   int64              `json:"TimeStamp"`
	From        int                `json:"From"`
}

type startPrintDataInner struct {
	Filename   string `json:"Filename"`
	StartLayer int    `json:"StartLayer"`
}

// buildStartPrintMessage constructs the Cmd 128 JSON payload.
// idUUID and requestUUID should be distinct UUIDs generated by the caller.
func buildStartPrintMessage(mainboardID, filename string, startLayer int, idUUID, requestUUID string, nowUnixSec int64) ([]byte, error) {
	p := startPrintPayload{
		ID: idUUID,
		Data: startPrintDataOuter{
			Cmd: 128,
			Data: startPrintDataInner{
				Filename:   filename,
				StartLayer: startLayer,
			},
			RequestID:   requestUUID,
			MainboardID: mainboardID,
			TimeStamp:   nowUnixSec,
			From:        0,
		},
		Topic: fmt.Sprintf("sdcp/request/%s", mainboardID),
	}
	return json.Marshal(p)
}

// ---------------------------------------------------------------------------
// subscribe message (Cmd 0)
// ---------------------------------------------------------------------------

// buildSubscribeMessage builds the Cmd 0 topic-subscribe JSON payload.
func buildSubscribeMessage(mainboardID, idUUID, requestUUID string, nowUnixSec int64) ([]byte, error) {
	p := map[string]any{
		"Id": idUUID,
		"Data": map[string]any{
			"Cmd":         0,
			"Data":        map[string]any{},
			"RequestID":   requestUUID,
			"MainboardID": mainboardID,
			"TimeStamp":   nowUnixSec,
			"From":        0,
		},
		"Topic": fmt.Sprintf("sdcp/status/%s", mainboardID),
	}
	return json.Marshal(p)
}

// ---------------------------------------------------------------------------
// StartPrint — connect, send Cmd 128, close
// ---------------------------------------------------------------------------

// startPrintResult is the outcome of startPrintWithDialer.
type startPrintResult struct {
	OK      bool
	Reason  string // timeout|unreachable|unknown
	Details string
}

// startPrint connects to the printer WebSocket and sends Cmd 128. It uses the
// real gorilla dialer. dialFn may be overridden in tests.
func startPrint(
	ctx context.Context,
	cfg ConnectionConfig,
	filename string,
	idUUID, requestUUID string,
	timeoutMs int,
	log *slog.Logger,
) startPrintResult {
	return startPrintWithDialer(ctx, cfg, filename, idUUID, requestUUID, timeoutMs, log, nil)
}

func startPrintWithDialer(
	ctx context.Context,
	cfg ConnectionConfig,
	filename string,
	idUUID, requestUUID string,
	timeoutMs int,
	log *slog.Logger,
	dialFn func(rawURL string) (wsConn, error),
) startPrintResult {
	if log == nil {
		log = slog.Default()
	}

	rawURL := fmt.Sprintf("ws://%s:%d/websocket", cfg.IP, cfg.Port)

	var conn wsConn
	if dialFn != nil {
		var err error
		conn, err = dialFn(rawURL)
		if err != nil {
			return mapDialError(err)
		}
	} else {
		dialer := websocket.Dialer{
			HandshakeTimeout: time.Duration(timeoutMs) * time.Millisecond,
		}
		wsC, _, err := dialer.DialContext(ctx, rawURL, nil)
		if err != nil {
			return mapDialError(err)
		}
		conn = &gorillaConn{conn: wsC}
	}
	defer conn.Close()

	msg, err := buildStartPrintMessage(
		cfg.MainboardID,
		"/local/"+filename,
		cfg.StartLayer,
		idUUID,
		requestUUID,
		time.Now().Unix(),
	)
	if err != nil {
		return startPrintResult{
			Reason:  "unknown",
			Details: fmt.Sprintf("build Cmd 128 payload: %s", err.Error()),
		}
	}

	if err := conn.WriteMessage(msg); err != nil {
		log.Warn("sdcp-commander: send Cmd 128 failed",
			"ip", cfg.IP, "mainboardId", cfg.MainboardID, "err", err.Error())
		return mapWriteError(err)
	}

	log.Info("sdcp-commander: Cmd 128 sent",
		"ip", cfg.IP, "mainboardId", cfg.MainboardID,
		"filename", filename, "startLayer", cfg.StartLayer,
	)
	return startPrintResult{OK: true}
}

// ---------------------------------------------------------------------------
// Error mapping helpers
// ---------------------------------------------------------------------------

func mapDialError(err error) startPrintResult {
	if isNetDialErrorForWS(err) {
		return startPrintResult{Reason: "unreachable", Details: err.Error()}
	}
	if errors.Is(err, context.DeadlineExceeded) {
		return startPrintResult{Reason: "timeout", Details: err.Error()}
	}
	// gorilla wraps timeouts as *net.OpError with Timeout()=true, also check.
	var opErr *net.OpError
	if errors.As(err, &opErr) && opErr.Timeout() {
		return startPrintResult{Reason: "timeout", Details: err.Error()}
	}
	return startPrintResult{Reason: "unknown", Details: err.Error()}
}

func mapWriteError(err error) startPrintResult {
	if isNetDialErrorForWS(err) {
		return startPrintResult{Reason: "unreachable", Details: err.Error()}
	}
	return startPrintResult{Reason: "unknown", Details: err.Error()}
}

func isNetDialErrorForWS(err error) bool {
	if err == nil {
		return false
	}
	var opErr *net.OpError
	if errors.As(err, &opErr) {
		return true
	}
	var dnsErr *net.DNSError
	return errors.As(err, &dnsErr)
}
